name       : apache-maven
version    : 3.5.2
release    : 5
source     :
    - https://github.com/apache/maven/archive/maven-3.5.2.tar.gz : e48ecefcefb6270ca632ffd3f67042a0842d498dee1b09b48cb8ffbfc9655e5c
license    : Apache-2.0
component  : programming.java
summary    : Apache Maven is a software project management and comprehension tool.
description: |
    Maven is a software project management and comprehension tool. Based on the concept of a Project Object Model (POM), Maven can manage a project's build, reporting and documentation from a central piece of information.
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-8
build      : |
    mvn -DdistributionTargetDir=$installdir/usr/share/apache-maven -Dmaven.repo.local=../local-repo clean package
install    : |
    mkdir -p $installdir/usr/bin
    ln -s /usr/share/apache-maven/bin/mvn $installdir/usr/bin/mvn
    ln -s /usr/share/apache-maven/bin/mvnDebug $installdir/usr/bin/mvnDebug
