name       : apache-maven
version    : 3.6.1
release    : 9
source     :
    - https://github.com/apache/maven/archive/maven-3.6.1.tar.gz : 00554d275731ab87bed6739779979acf01d315f58d3a2d91ace7170613bb5217
license    : Apache-2.0
component  : programming.java
summary    : Apache Maven is a software project management and comprehension tool.
description: |
    Maven is a software project management and comprehension tool. Based on the concept of a Project Object Model (POM), Maven can manage a project's build, reporting and documentation from a central piece of information.
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-8
build      : |
    mvn -DdistributionTargetDir=$installdir/usr/share/apache-maven -Dmaven.repo.local=../local-repo clean package
install    : |
    mkdir -p $installdir/usr/bin
    ln -s /usr/share/apache-maven/bin/mvn $installdir/usr/bin/mvn
    ln -s /usr/share/apache-maven/bin/mvnDebug $installdir/usr/bin/mvnDebug
