name       : apache-maven
version    : 3.6.2
release    : 11
source     :
    - https://github.com/apache/maven/archive/maven-3.6.2.tar.gz : 9dfab7ff5c9f49201631512f9a8c5148f50ba92776dd2b86b36077bd7eefbf2e
license    : Apache-2.0
component  : programming.java
summary    : A software project management and comprehension tool
description: |
    Maven is a software project management and comprehension tool. Based on the concept of a Project Object Model (POM), Maven can manage a project's build, reporting and documentation from a central piece of information.
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-8
setup      : |
    %patch -p1 < $pkgfiles/0001-Default-to-openjdk-8.patch
build      : |
    # Can be removed in release 12. This is just for bootstrapping
    export JAVA_HOME=/usr/lib64/openjdk-8

    mvn -DdistributionTargetDir=$installdir/usr/share/apache-maven -Dmaven.repo.local=../local-repo clean install
install    : |
    install -dm00755 $installdir/usr/bin
    ln -s /usr/share/apache-maven/bin/mvn $installdir/usr/bin/mvn
    ln -s /usr/share/apache-maven/bin/mvnDebug $installdir/usr/bin/mvnDebug

    # Remove non-Linux files and legal stuff
    find $installdir/usr/share/apache-maven \( -name 'README*' -o -iname '*license' -o -name NOTICE -o -name '*.cmd' \) -delete
    find $installdir/usr/share/apache-maven/lib/jansi-native -mindepth 1 -maxdepth 1 -type d -not -name linux64 -exec rm -rfv {} +
    rmdir $installdir/usr/share/apache-maven/lib/ext
