name       : apache-maven
version    : 3.8.4
release    : 16
source     :
    - https://github.com/apache/maven/archive/maven-3.8.4.tar.gz : 41031e3dfcb0d75d99a5615c988bab3d2d2819c98482eb5d17a877c758925c02
license    : Apache-2.0
component  : programming.java
summary    : A software project management and comprehension tool
description: |
    Maven is a software project management and comprehension tool. Based on the concept of a Project Object Model (POM), Maven can manage a project's build, reporting and documentation from a central piece of information.
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-11
setup      : |
    %patch -p1 < $pkgfiles/0001-Default-to-openjdk-11.patch
build      : |
    mvn -DdistributionTargetDir=$installdir/usr/share/apache-maven -Dmaven.repo.local=../local-repo clean install
install    : |
    install -dm00755 $installdir/usr/bin
    ln -s /usr/share/apache-maven/bin/mvn $installdir/usr/bin/mvn
    ln -s /usr/share/apache-maven/bin/mvnDebug $installdir/usr/bin/mvnDebug

    # Remove non-Linux files and legal stuff
    find $installdir/usr/share/apache-maven \( -name 'README*' -o -iname '*license' -o -name NOTICE -o -name '*.cmd' \) -delete
    find $installdir/usr/share/apache-maven/lib/jansi-native -mindepth 1 -maxdepth 1 -type d -not -name linux64 -exec rm -rfv {} +
    rmdir $installdir/usr/share/apache-maven/lib/ext
