name       : apache-maven
version    : 3.3.9
release    : 2
source     :
    - http://ftp.ps.pl/pub/apache/maven/maven-3/3.3.9/source/apache-maven-3.3.9-src.tar.gz : 9150475f509b23518e67a220a9d3a821648ab27550f4ece4d07b92b1fc5611bc
license    : Apache-2.0
component  : programming.java
summary    : Apache Maven is a software project management and comprehension tool.
description: |
    Maven is a software project management and comprehension tool. Based on the concept of a Project Object Model (POM), Maven can manage a project's build, reporting and documentation from a central piece of information.
builddeps  :
   - apache-ant
rundeps    :
   - openjdk-8
build      : |
    ant -Dmaven.home=$installdir/usr/share/apache-maven
install    : |
    mkdir -p $installdir/usr/bin
    ln -s /usr/share/apache-maven/bin/mvn $installdir/usr/bin/mvn
    ln -s /usr/share/apache-maven/bin/mvnDebug $installdir/usr/bin/mvnDebug
